In [26]:
# Importação das bibliotecas pandas e numpy para manipulação e análise de dados
import pandas as pd
import numpy as np

# Análise de Dados de Obesidade
Este notebook irá analisar dados de obesidade em diferentes países ao longo dos anos

In [27]:
# Carregamento do dataset de obesidade a partir do arquivo CSV
df_obesity = pd.read_csv(r'data/obesity_cleaned.csv')
df_obesity.head()

   Unnamed: 0      Country  Year    Obesity (%)         Sex
0           0  Afghanistan  1975  0.5 [0.2-1.1]  Both sexes
1           1  Afghanistan  1975  0.2 [0.0-0.6]        Male
2           2  Afghanistan  1975  0.8 [0.2-2.0]      Female
3           3  Afghanistan  1976  0.5 [0.2-1.1]  Both sexes
4           4  Afghanistan  1976  0.2 [0.0-0.7]        Male

In [28]:
# Verificação da estrutura do dataset: tipos de dados, valores não nulos e uso de memória
df_obesity.info()

<class 'pandas.DataFrame'>
RangeIndex: 24570 entries, 0 to 24569
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   24570 non-null  int64
 1   Country      24570 non-null  str
 2   Year         24570 non-null  int64
 3   Obesity (%)  24570 non-null  str
 4   Sex          24570 non-null  str
dtypes: int64(2), str(3)
memory usage: 959.9 KB

In [29]:
# Análise da coluna 'Unnamed: 0' para verificar se contém valores únicos ou repetidos
# Esta verificação ajuda a decidir se a coluna deve ser removida
df_obesity['Unnamed: 0'].value_counts()

Unnamed: 0
0        1
1        1
2        1
3        1
4        1
        ..
24565    1
24566    1
24567    1
24568    1
24569    1
Name: count, Length: 24570, dtype: int64

In [30]:
# Remoção da coluna 'Unnamed: 0' pois parece ser um índice desnecessário
# Parâmetro inplace=True modifica o DataFrame diretamente
df_obesity.drop(columns=['Unnamed: 0'], inplace=True)

In [31]:
# Inspeção da coluna 'Obesity (%)' para entender o formato dos dados
# Observa-se que os valores contêm números e intervalos entre colchetes
df_obesity['Obesity (%)']

0           0.5 [0.2-1.1]
1           0.2 [0.0-0.6]
2           0.8 [0.2-2.0]
3           0.5 [0.2-1.1]
4           0.2 [0.0-0.7]
               ...
24565       4.5 [2.4-7.6]
24566    24.8 [18.9-31.3]
24567    15.5 [12.0-19.2]
24568       4.7 [2.5-8.0]
24569    25.3 [19.1-32.0]
Name: Obesity (%), Length: 24570, dtype: str

In [32]:
# Extração apenas do valor numérico da coluna 'Obesity (%)'
# Usa split para separar pelo espaço e pega apenas a primeira parte (o valor principal)
df_obesity['Obesity %'] = df_obesity['Obesity (%)'].str.split(' ', expand=True)[0]

In [33]:
# Análise da distribuição dos valores na nova coluna 'Obesity %'
# normalize=True mostra a proporção de cada valor em relação ao total
df_obesity['Obesity %'].value_counts(normalize=True)

Obesity %
No      0.020513
0.4     0.009035
0.6     0.008873
0.5     0.008832
0.7     0.008547
          ...
54.2    0.000041
55.3    0.000041
48.1    0.000041
42.7    0.000041
46.5    0.000041
Name: proportion, Length: 602, dtype: float64

In [34]:
# Limpeza e conversão dos dados da coluna 'Obesity %':
# 1. Substitui valores 'No' por NaN (valores ausentes)
# 2. Remove valores NaN com dropna()
# 3. Converte a coluna para tipo numérico (float)
# 4. Garante que a coluna 'Year' seja do tipo inteiro
df_obesity.loc[df_obesity['Obesity %'] == 'No', 'Obesity %'] = np.nan
df_obesity['Obesity %'] = df_obesity['Obesity %'].dropna()
df_obesity['Obesity %'] = df_obesity['Obesity %'].astype(float)
df_obesity['Year'] = df_obesity['Year'].astype(int)

In [35]:
# Verificação final da estrutura do DataFrame após as limpezas
# Confirma os tipos de dados e a contagem de valores não nulos
df_obesity.info()

<class 'pandas.DataFrame'>
RangeIndex: 24570 entries, 0 to 24569
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Country      24570 non-null  str
 1   Year         24570 non-null  int64
 2   Obesity (%)  24570 non-null  str
 3   Sex          24570 non-null  str
 4   Obesity %    24066 non-null  float64
dtypes: float64(1), int64(1), str(3)
memory usage: 959.9 KB

In [36]:
# Define a coluna 'Year' como índice do DataFrame para facilitar análises temporais
# inplace=True modifica o DataFrame diretamente
df_obesity.set_index('Year', inplace=True)

Qual o percentual médio de obesidade por sexo no mundo no ano de 2015?

In [37]:
# Resposta à questão: Filtra dados do ano 2015 e agrupa por sexo para calcular a média
# numeric_only=True garante que apenas colunas numéricas sejam incluídas no cálculo
df_obesity[df_obesity.index == 2015].groupby('Sex').mean(numeric_only=True)

            Obesity %
Sex
Both sexes  19.508377
Female      22.899476
Male        15.980628

In [38]:
# Célula vazia para futuras análises ou expansões do projeto